### PR TITLE
Add support for an existing companion object

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Please let me know, I'm happy to revisit this.

**Comment by milessabin** [comment]
This seems like a huge change for something which my gut tells me should be quite minor ... could you walk me through it a little?

**Comment by dwijnand** [comment]
Its size shrinks considerably if you drop the indentation differences: https://github.com/milessabin/macro-compat/pull/18/files?w=1

**Comment by milessabin** [comment]
Ahh ... yes. I'd also forgotten that you'd need to merge an existing companion with the synthetic one which accounts for the rest.

OK, this looks good. I'm going to be really picky though and ask for the whitespace changes to be minimized before I merge, esp. reverting the horizontal alignment of the `=>`'s in case expressions ... I'd be compelled to remove it the next time I touch that file, so it only makes for noise in the history.

**Comment by dwijnand** [comment]
Absolutely.

**Comment by dwijnand** [comment]
Re-written and pushed.

**Comment by milessabin** [comment]
Awesome! Many thanks ... merging :-)

**Pull request merged**
