### PR TITLE
Configure MiMa's previousArtifacts to be less fragile to Scala version changes

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by milessabin** [comment]
Isn't that always true?

**Comment by dwijnand** [comment]
Not for pre-releases.

**Comment by dwijnand** [comment]
Here's a few examples in `consoleProject`:

``` scala
scala> CrossVersion isScalaApiCompatible "2.12.0-M5"
res0: Boolean = false

scala> CrossVersion isScalaApiCompatible "2.12.0-RC1"
res1: Boolean = false

scala> CrossVersion isScalaApiCompatible "2.12.0"
res2: Boolean = true

scala> CrossVersion isScalaApiCompatible "2.12.0-1"
res3: Boolean = true

scala> CrossVersion isScalaApiCompatible "2.12.1-M1"
res4: Boolean = true

scala> CrossVersion isScalaApiCompatible "2.12.1-RC1"
res5: Boolean = true

scala> CrossVersion isScalaApiCompatible "2.12.1"
res6: Boolean = true
```

**Comment by milessabin** [comment]
Is it true that the value of `CrossVersion isScalaApiCompatible scalaVersion` uniquely determined by the values of `CrossVersion` and `scalaVersion`? If it is then I don't see how this can work: whether or not there's a previous artefact is partly determined by what's been published to Central.

**Comment by milessabin** [comment]
What happens when 2.12.0 is released and we go to publish 1.1.1 for 2.12.0? If I'm reading the above correctly `CrossVersion isScalaApiCompatible "2.12.0"` will be true, so MiMa will expect a previous artefact. But that's the artefact we're trying build, so it won't be found?

**Comment by dwijnand** [comment]
It's true that whether or not there's a previous artefact is partly
determined by what's been published to Central, but at least with this we
can "fail fast" by realising it's pointless to even look for one for values
of Scala versions that don't guarantee compatibility.

And yes, you're right, when transitioning from pre-release to stable
release you'd have to toggle previous artefacts temporarily.

**Comment by milessabin** [comment]
Given that we're still going to need to think and possibly manually intervene to get this right I'm not convinced it would actually help: on balance I think I'd prefer a fully manual process to one which is automatic, but only sometimes.

I'm open to persuasion, but I think that the status quo is sufficiently OK that I don't feel particularly motivated to change it.

**Comment by dwijnand** [comment]
That's fine, no sweat.

**Pull request closed without merging**
