### PR TITLE
Update scala 2.13.0-RC2 to 2.13.0

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by milessabin** [comment]
Why the JDK change?

**Comment by Philippus** [comment]
The new Travis default build environment 'xenial' is being rolled out (https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476), which does not seem to support oraclejdk8 (at least not in the 'standard' way).
Some more details are in this thread: https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345.
Another option is to keep using 'trusty' for now, by setting `dist: trusty`.

**Comment by Avasil** [comment]
Seems like there is `2.13.0` already, would be great to have it released!

**Review by larsrh — APPROVED** [review]

**Comment by milessabin** [comment]
I've been pondering this one and have decided that while I will publish macro-compat for 2.13.0 if absolutely necessary, I'd prefer it if people moved away from it for Scala versions > 2.10.x by either dropping Scala 2.10 support, or by using a similar mechanism to the one used by shapeless and a few other projects.

**Comment by Atry** [comment]
According to the statistics on Maven Central repository, Binding.scala for Scala 2.10 still has a lot of downloads right now.

**Comment by milessabin** [comment]
@Atry I don't follow ... what is Binding.scala and how would not publishing macro-compat for 2.13.0 affect it?

macro-compat for 2.10 isn't going away. All I'm proposing is to not publish what is, in effect, a no-op annotation for Scala 2.13.0.

**Comment by Atry** [comment]
Binding.scala supports 2.10 to 2.12. It depends on sde, which depends on macro-compat.
If I want to publish Binding.scala for 2.13, I need macro-compat 2.13

**Comment by milessabin** [comment]
No I don't think you do. The macro-annotations in >= 2.11 are supposed to be completely erased from binary artefacts, so replacing them with locally defined annotations, as per shapeless should be fine.

I say "are supposed to be" because it's possible that something went wrong and they aren't. That would be a bug, but most likely not one I want to fix in a piece of software which I believe is largely obsolete.

**Comment by Atry** [comment]
Even if the all the API are dummy in macro-compat for Scala 2.13, we still need the class `macrocompat.bundle` to compile.

**Comment by milessabin** [comment]
That's not supposed to be necessary. Have you tried it?

**Comment by SethTisue** [comment]
for whatever it's worth, Scala 2.13 is not intended to support cross-building against 2.10, only against 2.11 and 2.12. trying to cross-build across all four versions is not normal practice.

**Comment by milessabin** [comment]
@Atry see [here](https://github.com/milessabin/macro-compat/blob/master/core/src/main/scala_2.11%2B/macrocompat/bundle_2.11.scala#L32-L34) ... the macro annotation completely erases itself on Scala >= 2.11 ... it's not supposed to leave any trace in binary artefacts.

**Comment by milessabin** [comment]
The reason for having the _local_ definition in shapeless is for _source_ compatibility when cross-building.

**Comment by Atry** [comment]
I wonder how local definition improves source compatibility?

**Comment by milessabin** [comment]
If you want to use macro-compat for 2.10 you will need `@bundle` annotation in your sources. That means you need _something_ for 2.13. The local definition does the job.

**Comment by Atry** [comment]
Is it really necessary to ask all macro-compat users create their own local `bundle` annotations?

**Comment by milessabin** [comment]
The other option is to drop 2.10 support. At this point in the 2.10 grieving process I think it's right to start encouraging people to move on.

**Comment by SethTisue** [comment]
> According to the statistics on Maven Central repository, Binding.scala for Scala 2.10 still has a lot of downloads right now.

that proves that there are still 2.10 users out there, but it doesn't prove that those users need — or even want! — new versions of all their other dependencies

also, I don't know about your library download numbers in particular, but speaking generally about 2.10 download stats, many of what might seem to be "2.10 users" are actually just people depending on things from sbt plugins in their legacy sbt 0.13.x builds, rather than people actively "using 2.10" in the usual sense of "using"

**Comment by limansky** [comment]
@SethTisue  I suppose people who use macro-compat (me, for example), just provide their libraries for Scala 2.10 because they get it allmost for free with macro-compat. At the same time I don't see any reason to keep using 2.10 in production projects.

**Comment by limansky** [comment]
@milessabin what is not clean, why it should be removed right now, once it's works fine for 2.13.0-RC2?

**Comment by milessabin** [comment]
@limansky because I want to discourage its use.

**Comment by Philippus** [comment]
@milessabin shall we close the PR?

**Comment by milessabin** [comment]
@Philippus sorry, I should have come back to you sooner. Yes, I'll close.

**Pull request closed without merging**
