### PR TITLE
Add Scala Native support

### LINKED ISSUE #78: Scala Native support
I wanted to add Scala Native support to Minitest, but realized that macro-compat is not available for Scala Native.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #78

### CODE REVIEW

**Comment by milessabin** [comment]
Happy to merge this, but it's going to be a real pain to retrospectively publish native builds of 1.1.1 and I've pretty much made up my mind that that will be the last macro-compat version. If you want 1.1.1 native builds could you backport this to all the relevant branches?

**Comment by eed3si9n** [comment]
Thankfully Scala Native only has 2.11, so I suggest we make another one of v1.1.1-scala-2.13.0-M4-ish branch off of v1.1.1-scala-2.13.0-M4.

**Comment by milessabin** [comment]
OK, that works for me.

**Comment by eed3si9n** [comment]
Here you go:
https://github.com/milessabin/macro-compat/compare/v1.1.1-scala-2.13.0-M4...eed3si9n:wip/1.1.1-native0.3-scala-2.11?expand=1

**Pull request merged**
