### PR TITLE
Enable real functionality of @compileTimeOnly for Scala 2.10

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by milessabin** [comment]
Very annoying that this change isn't binary compatible. Can you think of any workarounds?

**Comment by Atry** [comment]
IIRC, `@bridge` will keep the class file while make it invisible from AST

**Comment by Atry** [comment]
I tried some workarounds, which do not work.

How about merge this PR into the next major version of macro-compat?

**Comment by milessabin** [comment]
Sorry about the delay replying to your last comment ...

Yes, we can merge in the next major version :-)

**Comment by milessabin** [comment]
I don't think there will be a next major version ... continuing support for 2.10 macros isn't worth the effort at this point.

**Pull request closed without merging**
