### PR TITLE
Add c.ImplicitCandidate. Fixes #22

### LINKED ISSUE #22: Missing c.ImplicitCandidate
As used by [Generic1Macros](https://github.com/milessabin/shapeless/blob/5289c969064321f1e1aa9b3dd24f134f216ed1a9/core/src/main/scala/shapeless/generic1.scala#L156-L166).

If you know what the 2.10 equivalent is I can send the pull request. Thanks.

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
I'm having trouble using this however: https://gitter.im/milessabin/macro-compat?at=564b83d0c3e9f31e2bf3c395

**Comment by milessabin** [comment]
The failing MiMa check is safe to filter out (additions to the `MacroCompat` trait should be fine in general).

**Comment by milessabin** [comment]
Is this one dead?

**Comment by dwijnand** [comment]
It currently needs a way to fix the alias, which needs to link the original c outside of Stub, which you said you'd need to play around with a bit..

Haven't found any alternatives, it's still a blocker for sharing sources in Shapeless.

**Comment by milessabin** [comment]
Oh, right, OK, I'll look at that today :-)

**Comment by dwijnand** [comment]
Thanks.

**Comment by dwijnand** [comment]
Superseeded by https://github.com/milessabin/macro-compat/commit/af16d5eb6f64f7312b3398daebf8d259fa060272

**Pull request closed without merging**
