### PR TITLE
Add internal.typeRef

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Uhhhhh :(

```
[error] /Users/dnw/dev/shapeless-2.10/core/src/main/scala/shapeless/singletons.scala:329: reference to typeRef is ambiguous;
[error] it is imported twice in the same scope by
[error] import internal._
[error] and import c.universe._
[error]             typeRef(NoPrefix, tc2.typeSymbol, args)
[error]             ^
[error] one error found
```

**Comment by dwijnand** [comment]
Ah, it's ok I'll just change it to `c.internal.typeRef` instead

**Comment by milessabin** [comment]
Is this good to merge as is?

**Comment by dwijnand** [comment]
Yeah I'd say so, it's just a (hopefully small/rare) pitfall to avoid.

**Comment by milessabin** [comment]
Cool ... merging :-)

**Pull request merged**
